### ISSUE TITLE
Optionally avoiding Upstreaming

### ISSUE THREAD

**Issue by lucaparisi91** [ARCHER2-HPC/archer2-spack#1]
Currently the environment is setup so that site configuration is used.
Users can override the configuration, but it is not clear how to avoid upstreaming. Packages installed upstream can in some cases clash with locally installed packages.

- Generate modules do not preload from upstream
- Confusion when loading a module and having to pick between the centrally installed package and a user package with the same name but slight different spec . Can use `-N` flag or ashes do differentiate , but it is a confusing process. I expect many users will want a cleaner setup

**Comment by lucaparisi91** [comment]
The process might involve saving a spack lock file for portably transferring the whole environment.

**Comment by welucas2** [comment]
The current config setup for users is determined by `SPACK_SYSTEM_CONFIG_PATH` which is exported when loading the `spack` module. This points to the directory containing the config YAMLs, which is `config/archer2-user`. This leaves `SPACK_USER_CONFIG_PATH` (which is higher priority than the system config) available for users to set to whatever one of their own directories they want, which can contain YAMLs for whatever options they want to set.

@lucaparisi91, my proposal is to delete `config/archer2-user/upstreams.yaml` so that no upstreaming takes place by default. Then we would put it in documentation so those users who _do_ want to upstream can add it to a user config and set `SPACK_USER_CONFIG_PATH`.

The remaining configs in `config/archer2-user` are to help Spack use the ARCHER2 compilers and libraries. If users didn't want these, I think they would be better off just using vanilla Spack. Does this conflict with what you had in mind?

**Comment by lucaparisi91** [comment]
We deicded to not upstream
